### ISSUE TITLE
Feature/test request: benchmarks of dataclassframe's operations. 

### ISSUE THREAD

**Issue by SKalt** [joshlk/dataclassframe#2]
I think benchmarking DataClassFrame's operations would be a valuable addition to the project's test suite, especially given that the README claims: 
> [dataclassframe provides certain benefits] while having the efficiency of Pandas dataframes.

I think both direct comparisons and comparisons of the time complexities of DataClassFrame's operations to DataFrame's operations would attract users.

However, full disclosure: I'm not planning on writing these benchmarks in the near future.  As such, I don't have any expectations that anyone else will work on it.  Please close this issue if benchmark testing isn't on your near-term roadmap.

**Comment by joshlk** [comment]
Hi @SKalt,

Thank you for your interest in the project 😃.

Most of the code is a wrapper around Pandas DataFrames and so there shouldn't be much of a performance cost compared to Pandas. Have a look for yourself. That being said its always good test and measure your assumptions. I might get round to doing this in the future and so going to leave the issue open.

Thanks again for your support,
Josh
